name: flutterbasictemplate
description: A new Flutter Applicattion architecture components

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  shared_preferences: ^0.5.8
  fluttertoast: 7.0.1
  provider: ^4.3.1
  connectivity: ^0.4.9
  cached_network_image: ^2.2.0+1
  getwidget: ^1.1.0









dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

